### ISSUE TITLE
Bug: Renaming an item can cause duplication

### ISSUE THREAD

**Issue by ranndev** [blacksag/To-Dos#10]
**How to reproduce**

1. Create a first item and name it `'task 1'`
2. Create a second item and name it `'task 2'`
3. Rename the first item (`'task 1'`) to `'task 2'`

Now we have two items with same names.

**Comment by ranndev** [comment]
Fixing the issue now.

**Comment by blacksag** [comment]
Great catch! Will review the changes.

**Comment by blacksag** [comment]
It does check for duplicate names of task but generates an alert that says "Enter some value!" as it invoked "emptyHandler()". A new handler should be created and called when the case match.
