### ISSUE TITLE
Enable `Enter` key to trigger the operation

### ISSUE THREAD

**Issue by ranndev** [blacksag/To-Dos#25]
### Current behavior

Users are required to click the button to add, edit, delete and toggle an item.

### Expected behavior

Pressing `Enter` should also do the operation.
For the `Change` operation, its two respective inputs should be filled out first.

**Comment by variable5707** [comment]
resolved the issue you can add a item by press a enter key

**Comment by blacksag** [comment]
PR #28 might solve this issue
