### ISSUE TITLE
Improvement in UI

### ISSUE THREAD

**Issue by blacksag** [blacksag/To-Dos#26]
Instead of a toggle button for each task, an animated responsive button/icon can be created instead of the checkbox icon.

![InkedScreenshot_LI](https://user-images.githubusercontent.com/36514625/66703122-de928900-ed2c-11e9-8ba5-c40abf0bb306.jpg)
Should look something like this:

<img width="332" alt="Screen" src="https://user-images.githubusercontent.com/36514625/66703132-f702a380-ed2c-11e9-8058-ef3351bc502f.png">

**Comment by msoq** [comment]
Hello, I can help with this :)

**Comment by ranndev** [comment]
Hi and welcome @mikalai-sokarau , you surely can! :smiley:

**Comment by blacksag** [comment]
Ressolved by #35
