### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by blacksag** [blacksag/To-Dos#38]
The delete button (`advanceDeleteButton` ) for each task can be replaced by a (red) dustbin.

**Comment by chadramsey** [comment]
I can take a look at this

**Comment by chadramsey** [comment]
I can take a look at this

**Comment by TimeTerminal** [comment]
@blacksag got a PR for you: https://github.com/blacksag/To-Dos/pull/39

**Comment by chadramsey** [comment]
@blacksag PR: https://github.com/blacksag/To-Dos/pull/40
Let me know if you'd like anything updated.
